openapi: 3.0.0
info:
  title: app-me-cloud-oauth-private
  version: '1.0'
  description: app-me-cloud OAuth関連API
servers:
  - url: 'http://localhost:3000'
paths:
  /oauth2/authorize:
    post:
      summary: 認可リクエスト
      operationId: post-authorize
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  temporary_token:
                    type: string
                    description: ワンタイムトークン。有効期限は10分
                  scope_description:
                    type: string
                    description: どのデータのアクセスのアクセス許可を得るのかユーザーに表示するための文字列。認可APIのscopeパラメータより判別
                required:
                  - temporary_token
                  - scope_description
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                response_type:
                  type: string
                  description: '"code" 固定値。将来的に別レスポンスも想定'
                scope:
                  type: string
                  description: |-
                    付与する権限。URLエンコードされた空白文字（%20）で区切って、複数のスコープを指定できるようにする
                    まずは"read_property"と"read_user"の2つを公開
                state:
                  type: string
                  description: CSRF対策。クライアント側で生成した任意の文字列
                redirect_uri:
                  type: string
                  description: |-
                    コールバックURL
                    事前にclientごとにコールバックURLは登録しておく。一致しなければエラー
                client_id:
                  type: string
                  description: 事前発行するID。連携先を判別する
                email:
                  type: string
                  description: ログインメールアドレス
                password:
                  type: string
                  description: ログインパスワード
              required:
                - response_type
                - scope
                - state
                - redirect_uri
                - client_id
                - password
                - email
      description: |
        認可リクエストAPI
        入力されたemail, passwordの照合と連携情報を受取る。
      tags:
        - OAuth
    parameters: []
  /oauth2/access_permission:
    post:
      summary: データアクセス許可確認
      tags:
        - OAuth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirect_uri:
                    type: string
                    description: |-
                      リダイレクトURLを返却。
                      リダイレクトURLに付与するクエリパラメータ

                      {redirect_uri}?code={生成したgrant}&state={認可APIで受け取った値をそのまま返却}

                      詳しくは公開APIのドキュメントに記載する
                required:
                  - redirect_uri
      operationId: post-access_permission
      description: |-
        ユーザーにデータアクセスの同意を得て、grantを要求
        レスポンスにコールバックURLを返却。クライアント側でリダイレクト処理する
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                temporary_id:
                  type: string
                  description: 認可APIで受け取った仮token
              required:
                - temporary_id
    parameters: []
  /oauth2/client:
    get:
      summary: 認可サービス情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_id:
                    type: string
                    description: 連携先ID
                  client_name:
                    type: string
                    description: 連携先名
                  client_icon_image:
                    type: string
                    description: 連携先サービスアイコン画像URL
                required:
                  - client_id
                  - client_name
      operationId: get-oauth2-client
      parameters:
        - schema:
            type: string
          in: query
          name: client_id
          description: 連携先ID
          required: true
      description: 連携サービスの情報を取得する
components:
  schemas: {}
